### ISSUE TITLE
add a hassio integeration

### ISSUE THREAD

**Issue by ohadlevy** [eyalcha/read_your_meter#2]
it would be nice if the required containers could be bundled as hassio (e.g. https://github.com/hassio-addons/addon-example)

Thanks!

**Comment by arnonsha** [comment]
+1 vote from me

Many people in the community run plain hass.io. I believe the hardest thing (at least for me) is sellenium, which I couldn't find how to install under hass.io.

thanks !

**Comment by Dmxsir** [comment]
> +1 vote from me
> 
> Many people in the community run plain hass.io. I believe the hardest thing (at least for me) is sellenium, which I couldn't find how to install under hass.io.
> 
> thanks !

You can install it from the ha cli.

**Comment by ohadlevy** [comment]
I'm not sure if the extension itself can run multiple containers, but at
worse you can install portainer and run it as well.

**Comment by ohadlevy** [comment]
or perhaps create two addons, one for selenium and another for the read your meter?

**Comment by arnonsha** [comment]
> > thanks !
> 
> You can install it from the ha cli.

I'd appreciate if you could be more specific on how to do that.
I need root privileges I believe which I don't have in the ha cli

**Comment by Dmxsir** [comment]
> 
> 
> > > thanks !
> > 
> > 
> > You can install it from the ha cli.
> 
> I'd appreciate if you could be more specific on how to do that.
> I need root privileges I believe which I don't have in the ha cli

from the `Terminal` addon just copy/past 
`docker run -d -p 4444:4444 --name selenium selenium/standalone-chrome`

then go to `portainer` addon ' and go to `selenium image/Container ` .
scroll down to `Restart policies` and change to `Always`, and click update.

**Comment by ohadlevy** [comment]
> from the `Terminal` addon just copy/past

docker is not available in the terminal (its just another container that mounts /config and can run the ha cli).

if you already have portainer, then you can install it from there to begin with..

**Comment by maorcc** [comment]
Due to the difficulty to install the required Selenium in Hassio, I've developed a simpler alternative implementation that has no dependencies and is trivial to setup with HACS.
Have a look at https://github.com/maorcc/citymind_water_meter
